/*
 * Party Role Management
 *
 * This is Swagger UI environment generated for the TMF Party Role Management specification
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace PartRoleManagementAPI.Dto
{
    /// <summary>
    /// Indicates the contact medium that could be used to contact the party.
    /// </summary>
    [DataContract]
    // [Keyless]
    public partial class ContactMediumDto : IEquatable<ContactMediumDto>
    {
        /// <summary>
        /// Type of the contact medium, such as: email address, telephone number, postal address
        /// </summary>
        /// <value>Type of the contact medium, such as: email address, telephone number, postal address</value>
        [JsonPropertyName("mediumType")]
        public string MediumType { get; set; }

        /// <summary>
        /// If true, indicates that is the preferred contact medium
        /// </summary>
        /// <value>If true, indicates that is the preferred contact medium</value>

        [JsonPropertyName("preferred")]
        public bool? Preferred { get; set; }

        /// <summary>
        /// Any additional characteristic(s) of this contact medium
        /// </summary>
        /// <value>Any additional characteristic(s) of this contact medium</value>

        [JsonPropertyName("characteristic")]
        public MediumCharacteristicDto Characteristic { get; set; }

        /// <summary>
        /// The time period that the contact medium is valid for
        /// </summary>
        /// <value>The time period that the contact medium is valid for</value>

        [JsonPropertyName("validFor")]
        public TimePeriodDto ValidFor { get; set; }

        /// <summary>
        /// When sub-classing, this defines the super-class
        /// </summary>
        /// <value>When sub-classing, this defines the super-class</value>

        [JsonPropertyName("@baseType")] 
        public string BaseType { get; set; } = string.Empty;

        /// <summary>
        /// A URI to a JSON-Schema file that defines additional attributes and relationships
        /// </summary>
        /// <value>A URI to a JSON-Schema file that defines additional attributes and relationships</value>

        [JsonPropertyName("@schemaLocation")] 
        public string SchemaLocation { get; set; } = string.Empty;

        /// <summary>
        /// When sub-classing, this defines the sub-class entity name
        /// </summary>
        /// <value>When sub-classing, this defines the sub-class entity name</value>

        [JsonPropertyName("@type")] 
        public string Type { get; set; } = string.Empty;

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ContactMedium {\n");
            sb.Append("  MediumType: ").Append(MediumType).Append("\n");
            sb.Append("  Preferred: ").Append(Preferred).Append("\n");
            sb.Append("  Characteristic: ").Append(Characteristic).Append("\n");
            sb.Append("  ValidFor: ").Append(ValidFor).Append("\n");
            sb.Append("  BaseType: ").Append(BaseType).Append("\n");
            sb.Append("  SchemaLocation: ").Append(SchemaLocation).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ContactMediumDto)obj);
        }

        /// <summary>
        /// Returns true if ContactMediumDto instances are equal
        /// </summary>
        /// <param name="other">Instance of ContactMediumDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ContactMediumDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    MediumType == other.MediumType ||
                    MediumType != null &&
                    MediumType.Equals(other.MediumType)
                ) &&
                (
                    Preferred == other.Preferred ||
                    Preferred != null &&
                    Preferred.Equals(other.Preferred)
                ) &&
                (
                    Characteristic == other.Characteristic ||
                    Characteristic != null &&
                    Characteristic.Equals(other.Characteristic)
                ) &&
                (
                    ValidFor == other.ValidFor ||
                    ValidFor != null &&
                    ValidFor.Equals(other.ValidFor)
                ) &&
                (
                    BaseType == other.BaseType ||
                    BaseType != null &&
                    BaseType.Equals(other.BaseType)
                ) &&
                (
                    SchemaLocation == other.SchemaLocation ||
                    SchemaLocation != null &&
                    SchemaLocation.Equals(other.SchemaLocation)
                ) &&
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (MediumType != null)
                    hashCode = hashCode * 59 + MediumType.GetHashCode();
                if (Preferred != null)
                    hashCode = hashCode * 59 + Preferred.GetHashCode();
                if (Characteristic != null)
                    hashCode = hashCode * 59 + Characteristic.GetHashCode();
                if (ValidFor != null)
                    hashCode = hashCode * 59 + ValidFor.GetHashCode();
                if (BaseType != null)
                    hashCode = hashCode * 59 + BaseType.GetHashCode();
                if (SchemaLocation != null)
                    hashCode = hashCode * 59 + SchemaLocation.GetHashCode();
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(ContactMediumDto left, ContactMediumDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ContactMediumDto left, ContactMediumDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
